### ISSUE TITLE
Position dialog in a static place so the title bar doesn't move around.

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/web-ui-renderer#2]
As its flipping between screens, it needs to be in a fixed position so that while the height is changing, the title bar remains in a static position on the page.

**Comment by deansallinen** [comment]
I've got it fixed to `30vh` in my branch, which keeps the title bar static, but with smaller viewports there's no compensation for larger height screens. It's possible the user will have to scroll to see the bottom of the dialog, depending on how we set the `max-height`. I'll continue to experiment and see if we can solve this with changing the max-height based on viewport height.

![image](https://user-images.githubusercontent.com/7519573/223509653-0b5ce513-b047-407c-88d0-d0fb0d7df9c5.png)

![image](https://user-images.githubusercontent.com/7519573/223509694-7bce7704-c3b6-464e-9dd0-b1b5f2cac5b9.png)
