### ISSUE TITLE
Login Modal not responsive to device-width

### ISSUE THREAD

**Issue by rakeden** [wharfkit/web-ui-renderer#21]
Testing on iPhone SE 2020 I found that the login modal is not fully responsive and exceeds the device width:
In this case 375 x 667 px

![wharfkit-iphone-se-2020](https://user-images.githubusercontent.com/5896201/230067470-9e57897c-4e4f-4f0e-98e8-66d474f484d9.jpg)

I suggest the modal is fully responsive and applies `max-width: [90-100]%`

**Comment by aaroncox** [comment]
We have a branch with UI improvements we're just awaiting review to merge https://github.com/wharfkit/web-ui-renderer/pull/7

I believe this will have a number of mobile optimizations in it, including a fix to the width.
