### ISSUE TITLE
Can we make the scroll bar always visible in this text area?

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/web-ui-renderer#57]
It's unclear that you can scroll, wondering if we could make it so the scroll bar always shows so they can see it?

<img width="538" alt="image" src="https://user-images.githubusercontent.com/677686/232330046-92828fc4-519c-4b39-9f57-2f29693a2e61.png">

**Comment by deansallinen** [comment]
Seems like browsers and OSes handle scrollbar visibility differently, and I haven't found an easy way to force scrollbars to stay visible in all situations. 

For MacOS, “Show scroll bars: Always” checked in General System Preferences apparently does the trick, but that's a user preference. 

We could do a custom scroller in JS, but we'd be adding complexity, weight, and maybe sacrificing some performance. 

A better option might be to design the textarea to give the affordance of scrollability, without the explicit scrollbar. We should bring this up on the next design call.

**Comment by aaroncox** [comment]
Boo, was hoping it was just a CSS setting 😉 

Oh well, we can punt this and deal with more critical things.
